layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: mubarak.daha
  linkedin: bagwai
  medium: "@mubarakdaha8"
  stackoverflow: 11452609
  twitter: Dr_Bagwai
  youtube: mubarakdaha8
  mail: mubarakdaha8@gmail.com

topics:
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: http://aux.iconspalace.com/uploads/1637531540241015194.png

  - name: HTML
    web_url: https://github.com/topics/html
    image_url: http://icons.iconarchive.com/icons/iconstoc/vintage-social/256/html-5-icon.png
  
  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://juststickers.in/wp-content/uploads/2019/01/flutter.png

  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://cdn.iconscout.com/icon/free/png-256/django-11-1175036.png



theme: jekyll-theme-slate